import type { Directory, Group, Role, User } from "./types";

export const SYSTEM_NAME = "Meridian Health Ops";

/** Groups that ship with the tenant. Used by tasks that forbid reusing them. */
export const SEED_GROUP_IDS = [
  "grp-clinical-staff",
  "grp-physicians",
  "grp-billing",
  "grp-billing-approvers",
  "grp-compliance",
  "grp-platform-admins",
  "grp-interns",
  "grp-helpdesk",
];

const roles: Role[] = [
  {
    id: "role-clinical-nurse",
    name: "Clinical Nurse",
    description: "Bedside charting and claim look-ups.",
    permissions: ["patients:read", "patients:update", "claims:read"],
    builtIn: true,
  },
  {
    id: "role-physician",
    name: "Physician",
    description: "Full clinical authoring plus claim submission.",
    permissions: [
      "patients:read",
      "patients:create",
      "patients:update",
      "claims:read",
      "claims:create",
    ],
    builtIn: true,
  },
  {
    id: "role-billing-analyst",
    name: "Billing Analyst",
    description: "Prepares invoices and works the claim queue.",
    permissions: [
      "invoices:read",
      "invoices:create",
      "claims:read",
      "claims:update",
      "reports:read",
      "patients:delete",
    ],
    builtIn: true,
  },
  {
    id: "role-billing-approver",
    name: "Billing Approver",
    description: "Releases prepared invoices to the payer.",
    permissions: ["invoices:read", "invoices:approve"],
    builtIn: true,
  },
  {
    id: "role-compliance-auditor",
    name: "Compliance Auditor",
    description: "Reads everything, exports for regulators.",
    permissions: [
      "patients:read",
      "patients:export",
      "claims:read",
      "reports:read",
      "reports:export",
    ],
    builtIn: true,
  },
  {
    id: "role-platform-admin",
    name: "Platform Admin",
    description: "Runs the tenant: accounts, configuration, integrations.",
    permissions: [
      "users:read",
      "users:create",
      "users:update",
      "users:delete",
      "settings:read",
      "settings:update",
      "reports:read",
    ],
    builtIn: true,
  },
  {
    id: "role-helpdesk",
    name: "Help Desk",
    description: "Password resets and profile fixes. No clinical writes.",
    permissions: ["users:read", "users:update", "patients:read"],
    builtIn: true,
  },
];

const groups: Group[] = [
  {
    id: "grp-clinical-staff",
    name: "Clinical Staff",
    description: "Everyone who touches a patient chart.",
    roleIds: ["role-clinical-nurse"],
    memberOf: [],
    builtIn: true,
  },
  {
    id: "grp-physicians",
    name: "Physicians",
    description: "Attending physicians. Nested inside Clinical Staff.",
    roleIds: ["role-physician"],
    memberOf: ["grp-clinical-staff"],
    builtIn: true,
  },
  {
    id: "grp-billing",
    name: "Billing",
    description: "Revenue cycle team.",
    roleIds: ["role-billing-analyst"],
    memberOf: [],
    builtIn: true,
  },
  {
    id: "grp-billing-approvers",
    name: "Billing Approvers",
    description: "Signs off on invoice runs.",
    roleIds: ["role-billing-approver"],
    memberOf: [],
    builtIn: true,
  },
  {
    id: "grp-compliance",
    name: "Compliance",
    description: "Regulatory reporting and audit response.",
    roleIds: ["role-compliance-auditor"],
    memberOf: [],
    builtIn: true,
  },
  {
    id: "grp-platform-admins",
    name: "Platform Admins",
    description: "Tenant owners.",
    roleIds: ["role-platform-admin"],
    memberOf: [],
    builtIn: true,
  },
  {
    id: "grp-interns",
    name: "Interns",
    description: "Summer cohort. Someone nested this somewhere it should not be.",
    roleIds: [],
    memberOf: ["grp-platform-admins"],
    builtIn: true,
  },
  {
    id: "grp-helpdesk",
    name: "Help Desk",
    description: "Tier-1 support.",
    roleIds: ["role-helpdesk"],
    memberOf: [],
    builtIn: true,
  },
];

const users: User[] = [
  {
    id: "u-dana",
    name: "Dana Whitfield",
    title: "Clinical Nurse (new hire)",
    email: "dana.whitfield@meridian.example",
    status: "active",
    groupIds: [],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-marcus",
    name: "Marcus Reyes",
    title: "Billing Analyst (departed)",
    email: "marcus.reyes@meridian.example",
    status: "active",
    groupIds: ["grp-billing", "grp-helpdesk"],
    roleIds: ["role-platform-admin"],
    builtIn: true,
  },
  {
    id: "u-aisha",
    name: "Aisha Rahman",
    title: "Senior Billing Analyst",
    email: "aisha.rahman@meridian.example",
    status: "active",
    groupIds: ["grp-billing", "grp-billing-approvers"],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-tom",
    name: "Tom Okafor",
    title: "Revenue Cycle Manager",
    email: "tom.okafor@meridian.example",
    status: "active",
    groupIds: ["grp-billing-approvers"],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-priya",
    name: "Priya Nair",
    title: "External contractor (analytics)",
    email: "priya.nair@northwind-consulting.example",
    status: "active",
    groupIds: ["grp-clinical-staff"],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-ben",
    name: "Ben Castellanos",
    title: "Intern",
    email: "ben.castellanos@meridian.example",
    status: "active",
    groupIds: ["grp-interns"],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-lena",
    name: "Lena Fischer",
    title: "Director of IT",
    email: "lena.fischer@meridian.example",
    status: "active",
    groupIds: ["grp-platform-admins"],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-sofia",
    name: "Sofia Marchetti",
    title: "Compliance Officer",
    email: "sofia.marchetti@meridian.example",
    status: "active",
    groupIds: ["grp-compliance"],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-raj",
    name: "Raj Patel",
    title: "Attending Physician",
    email: "raj.patel@meridian.example",
    status: "active",
    groupIds: ["grp-physicians"],
    roleIds: [],
    builtIn: true,
  },
  {
    id: "u-nora",
    name: "Nora Bell",
    title: "Help Desk Lead",
    email: "nora.bell@meridian.example",
    status: "active",
    groupIds: ["grp-helpdesk"],
    roleIds: ["role-compliance-auditor"],
    builtIn: true,
  },
];

export function seedDirectory(): Directory {
  return structuredClone({ users, groups, roles });
}
